name: Build and cache with Nix

on:
  workflow_dispatch:
  push:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Nix with caching
      uses: kadena-io/setup-nix-with-cache@v1
      with:
        cache_url: s3://nixcache.chainweb.com?region=us-east-1
        signing_private_key: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.NIX_CACHE_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.NIX_CACHE_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Not sure why nix cannot just do this for me (or does not want to do it) ...
    - name: Update nix sha values for source repository packages
      run: |
        nix-prefetch-git --url https://github.com/kadena-io/pact.git --rev 9bdbe3ae6a3a6fcb6da4c5ae5a924c941676388b
        nix-prefetch-git --url https://github.com/kadena-io/pact-json.git --rev f8314fe8313702b07102a9f8330ad91630d1b124
        nix-prefetch-git --url https://github.com/kadena-io/chainweb-storage.git --rev af9f42c78bcd703ac382cfd8101c6d1c66a035f1

    - name: Build and cache artifacts
      timeout-minutes: 740
      run: |
        echo Building the project and its devShell
        nix build .#check
